---
# tasks file for lamp-dep

- name: Install LAMP Stack Dep. 
  apt: name={{item}} state=present
  with_items:
  - apache2
  - mariadb-server
  - php
  - libapache2-mod-php
  - php-mcrypt
  - php-mysql
  - python-mysqldb


- name: Bring the MariaDB UP
  service: name=mysql state=started enabled=True

- name: Deploy MySQL Config
  template: src=templates/my.cnf.j2 dest=/root/.my.cnf
  run_once: true


- name: Set root password
  mysql_user: login_password={{mysql_root_password}} check_implicit_admin=yes name=root host={{item}} password={{mysql_root_password}}
  with_items:
  - localhost
  - 127.0.0.1
  - ::1


- name: Deploying Updated MYSQL Config
  template: src=templates/my.cnf-2.j2 dest=/root/.my.cnf


- name: Reload Privileg tables
  command: 'mysql -ne "{{item}}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False



- name: Remove Annoynomus user
  command: 'mysql -ne "{{item}}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False


- name: Disallow Root Login from remote
  command: 'mysql -ne "{{item}}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove Test Databse & access 
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%' 
  changed_when: False


- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False


- name: Setup WordPress DB
  mysql_db: name={{ wp_mysql_db }} state=present


- name: Create MariaDB User info. 
  mysql_user: 
    login_user=root
    login_password={{ mysql_root_password }}
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv='*.*:ALL,GRANT'
    state=present




